#!/bin/bash

here=$(readlink -f $0)
here=$(dirname "$0")
pre="$1"
out="$2"
dir=$(dirname $2)/ktime

if [ "$out" = "" -o "$pre" = "" ]
then
    echo "Invalid argument(s)"
    exit 1
fi

echo "#######################################################################################"
echo ""

post=$(mktemp)
md5=$(zcat $pre | dd skip=24 bs=1 count=32 2> /dev/null)

export KEMUFUZZER_KERNEL_VERSION="prot + pag"
export KEMUFUZZER_KERNEL_CHECKSUM="$md5"
export KEMUFUZZER_PRE_STATE="$pre"
export KEMUFUZZER_POST_STATE="$post"
export KEMUFUZZER_TESTCASE_CHECKSUM="no checksum"

tmpfile=$(mktemp)
{ TIMEFORMAT='%3R'; time $here/kvm $pre $post; } 2>$tmpfile
ret=$?
if [ $ret -eq 0 ]
then
	mv "$post" "$out"
else
	sed -i '$ d' $dir
fi

cat $tmpfile
cat $tmpfile >> $dir
rm -f "$post"
rm -f "$tmpfile"
exit $ret
