VEX_DIR=/home/yanxx297/Project/lib/vex-r2737
LIBASMIR_CXXFLAGS=-I/home/yanxx297/Project/lib/vex-r2737/pub -I/home/yanxx297/Project/nsf-EmuVerify/tools/fuzzball/src/include -g -O2
LIBASMIR_LDFLAGS=-L/home/yanxx297/Project/lib/vex-r2737 -L/home/yanxx297/Project/nsf-EmuVerify/tools/fuzzball/src 
LIBASMIR_LIBS=-lasmir -lvex -lbfd -liberty
