// Warning: this file has been automatically generated by gen_ints_asm.py

#include "interrupts.h"
#include <sys/tss.h>
#include "kernel.h"

extern int kprintf(const char *format, ...);
extern tss_t tss0;

static void set_idt_entry(idte_t *idt, uint8_t n, uint16_t seg, uint32_t off)
{
  idt[n].off_0_15 = off & 0xffff;
  idt[n].off_16_31 = (off>>16) & 0xffff;
  idt[n].seg = seg;
  idt[n].zero = 0;
  idt[n].type = 0xe; /* interrupt gate */
  idt[n].dpl = 3;
  idt[n].present = 1;
}

static void set_idt_entry_tss(idte_t *idt, uint8_t n, uint16_t seg)
{
  idt[n].seg = seg;
  idt[n].zero = 0;
  idt[n].type = 0x5; /* tss gate */
  idt[n].dpl = 0;
  idt[n].present = 1;
}

void set_interrupt_handlers(idte_t *pidt, uint16_t seg)
{
  set_idt_entry_tss(pidt, 0, SEL_EXCP00);
  set_idt_entry_tss(pidt, 1, SEL_EXCP01);
  set_idt_entry_tss(pidt, 2, SEL_EXCP02);
  set_idt_entry_tss(pidt, 3, SEL_EXCP03);
  set_idt_entry_tss(pidt, 4, SEL_EXCP04);
  set_idt_entry_tss(pidt, 5, SEL_EXCP05);
  set_idt_entry_tss(pidt, 6, SEL_EXCP06);
  set_idt_entry_tss(pidt, 7, SEL_EXCP07);
  set_idt_entry_tss(pidt, 8, SEL_EXCP08);
  set_idt_entry_tss(pidt, 9, SEL_EXCP09);
  set_idt_entry_tss(pidt, 10, SEL_EXCP10);
  set_idt_entry_tss(pidt, 11, SEL_EXCP11);
  set_idt_entry_tss(pidt, 12, SEL_EXCP12);
  set_idt_entry_tss(pidt, 13, SEL_EXCP13);
  set_idt_entry_tss(pidt, 14, SEL_EXCP14);
  set_idt_entry_tss(pidt, 15, SEL_EXCP15);
  set_idt_entry_tss(pidt, 16, SEL_EXCP16);
  set_idt_entry_tss(pidt, 17, SEL_EXCP17);
  set_idt_entry_tss(pidt, 18, SEL_EXCP18);
  set_idt_entry_tss(pidt, 19, SEL_EXCP19);
  set_idt_entry(pidt, 20, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 21, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 22, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 23, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 24, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 25, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 26, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 27, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 28, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 29, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 30, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 31, seg, (uint32_t)int_handler_null);
  set_idt_entry_tss(pidt, 32, SEL_EXCP32);
  set_idt_entry(pidt, 33, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 34, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 35, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 36, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 37, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 38, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 39, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 40, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 41, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 42, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 43, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 44, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 45, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 46, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 47, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 48, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 49, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 50, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 51, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 52, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 53, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 54, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 55, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 56, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 57, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 58, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 59, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 60, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 61, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 62, seg, (uint32_t)int_handler_null);
  set_idt_entry(pidt, 63, seg, (uint32_t)int_handler_null);
}

void int_handler_0(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
//  kprintf("interrupt handler 0 speaking\n");
    uint32_t *d = &(tss0.eip);
    asm volatile (
    		"begin0:"
    		"mov %%cr0,%%eax;"
    		"and $0x80000000,%%eax;"
    		"cmpl $0x80000000,%%eax;"
    		"je pg0;"
    		"movl $0x0,0x278010;"
                "mov 0x278008,%%eax;"
                "mov %%eax,%0;"
    		"jmp end0;"
    		"pg0:"
    		"movl $0x0,0x1278010;"
                "mov 0x1278008,%%eax;"
                "mov %%eax,%0;"
    		"end0:"
    		"iret;"
    		"jmp begin0;"
                : "=m" (*d));
  return;
}
void int_handler_1(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
//  kprintf("interrupt handler 1 speaking\n");
    uint32_t *d = &(tss0.eip);
    asm volatile (
    		"begin1:"
    		"mov %%cr0,%%eax;"
    		"and $0x80000000,%%eax;"
    		"cmpl $0x80000000,%%eax;"
    		"je pg1;"
    		"movl $0x1,0x278010;"
                "mov 0x278008,%%eax;"
                "mov %%eax,%0;"
    		"jmp end1;"
    		"pg1:"
    		"movl $0x1,0x1278010;"
                "mov 0x1278008,%%eax;"
                "mov %%eax,%0;"
    		"end1:"
    		"iret;"
    		"jmp begin1;"
                : "=m" (*d));
  return;
}
void int_handler_2(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
//  kprintf("interrupt handler 2 speaking\n");
    asm volatile (
    		"begin2:"
                "iret;"
                "jmp begin2;");
  return;
}
void int_handler_3(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
//  kprintf("interrupt handler 3 speaking\n");
    uint32_t *d = &(tss0.eip);
    asm volatile (
    		"begin3:"
    		"mov %%cr0,%%eax;"
    		"and $0x80000000,%%eax;"
    		"cmpl $0x80000000,%%eax;"
                "je pg3;"
    		"movl $0x3,0x278010;"
                "mov 0x278008,%%eax;"
                "mov %%eax,%0;"
    		"jmp end3;"
    		"pg3:"
    		"movl $0x3,0x1278010;"
                "mov 0x1278008,%%eax;"
                "mov %%eax,%0;"
    		"end3:"
    		"iret;"
    		"jmp begin3;"
                : "=m" (*d));
  return;
}
void int_handler_4(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
//  kprintf("interrupt handler 4 speaking\n");
    uint32_t *d = &(tss0.eip);
    asm volatile (
    		"begin4:"
    		"mov %%cr0,%%eax;"
    		"and $0x80000000,%%eax;"
    		"cmpl $0x80000000,%%eax;"
    		"je pg4;"
    		"movl $0x4,0x278010;"
                "mov 0x278008,%%eax;"
                "mov %%eax,%0;"
    		"jmp end4;"
    		"pg4:"
    		"movl $0x4,0x1278010;"
                "mov 0x1278008,%%eax;"
                "mov %%eax,%0;"
    		"end4:"
    		"iret;"
    		"jmp begin4;"
                : "=m" (*d));
  return;
}
void int_handler_5(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
//  kprintf("interrupt handler 5 speaking\n");
    asm volatile (
    		"begin5:"
                "iret;"
    		"jmp begin5;");
  return;
}
void int_handler_6(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
//  kprintf("interrupt handler 6 speaking\n");
    uint32_t *d = &(tss0.eip);
    asm volatile (
                "begin6:"
    		"mov %%cr0,%%eax;"
    		"and $0x80000000,%%eax;"
    		"cmpl $0x80000000,%%eax;"
    		"je pg6;"
    		"movl $0x6,0x278010;"
                "mov 0x278008,%%eax;"
                "mov %%eax,%0;"
    		"jmp end6;"
    		"pg6:"
    		"movl $0x6,0x1278010;"
                "mov 0x1278008,%%eax;"
                "mov %%eax,%0;"
    		"end6:"
    		"iret;"
    		"jmp begin6;"
                : "=m" (*d));
  return;
}
void int_handler_7(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
//  kprintf("interrupt handler 7 speaking\n");
    uint32_t *d = &(tss0.eip);
    asm volatile (
    		"begin7:"
    		"mov %%cr0,%%eax;"
    		"and $0x80000000,%%eax;"
    		"cmpl $0x80000000,%%eax;"
    		"je pg7;"
    		"movl $0x7,0x278010;"
                "mov 0x278008,%%eax;"
                "mov %%eax,%0;"
    		"jmp end7;"
    		"pg7:"
    		"movl $0x7,0x1278010;"
                "mov 0x1278008,%%eax;"
                "mov %%eax,%0;"
    		"end7:"
    		"iret;"
    		"jmp begin7;"
                : "=m" (*d));
  return;
}
void int_handler_8(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
//  kprintf("interrupt handler 8 speaking\n");
    uint32_t *d = &(tss0.eip);
	asm volatile (
    		"begin8:"
    		"mov %%cr0,%%eax;"
    		"and $0x80000000,%%eax;"
    		"cmpl $0x80000000,%%eax;"
    		"je pg8;"
    		"pop 0x27800c;"
    		"movl $0x8,0x278010;"
                "mov 0x278008,%%eax;"
                "mov %%eax,%0;"
    		"jmp end8;"
    		"pg8:"
    		"pop 0x127800c;"
    		"movl $0x8,0x1278010;"
                "mov 0x1278008,%%eax;"
                "mov %%eax,%0;"
    		"end8:"
    		"iret;"
    		"jmp begin8;"
                : "=m" (*d));
  return;
}
void int_handler_9(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
//  kprintf("interrupt handler 9 speaking\n");
    uint32_t *d = &(tss0.eip);
	asm volatile (
    		"begin9:"
    		"mov %%cr0,%%eax;"
    		"and $0x80000000,%%eax;"
    		"cmpl $0x80000000,%%eax;"
    		"je pg9;"
    		"movl $0x9,0x278010;"
                "mov 0x278008,%%eax;"
                "mov %%eax,%0;"
    		"jmp end9;"
    		"pg9:"
    		"movl $0x9,0x1278010;"
                "mov 0x1278008,%%eax;"
                "mov %%eax,%0;"
    		"end9:"
    		"iret;"
    		"jmp begin9;"
                : "=m" (*d));
  return;
}
void int_handler_10(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
//  kprintf("interrupt handler 10 speaking\n");
    uint32_t *d = &(tss0.eip);
	asm volatile (
    		"begin10:"
    		"mov %%cr0,%%eax;"
    		"and $0x80000000,%%eax;"
    		"cmpl $0x80000000,%%eax;"
    		"je pg10;"
    		"pop 0x27800c;"
    		"movl $0xa,0x278010;"
                "mov 0x278008,%%eax;"
                "mov %%eax,%0;"
    		"jmp end10;"
    		"pg10:"
    		"pop 0x127800c;"
    		"movl $0xa,0x1278010;"
                "mov 0x1278008,%%eax;"
                "mov %%eax,%0;"
    		"end10:"
    		"iret;"
    		"jmp begin10;"
                : "=m" (*d));
        return;
}
void int_handler_11(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
//  kprintf("interrupt handler 11 speaking\n");
    uint32_t *d = &(tss0.eip);
    asm volatile (
    		"begin11:"
    		"mov %%cr0,%%eax;"
    		"and $0x80000000,%%eax;"
    		"cmpl $0x80000000,%%eax;"
    		"je pg11;"
    		"pop 0x27800c;"
    		"movl $0xb,0x278010;"
                "mov 0x278008,%%eax;"
                "mov %%eax,%0;"
    		"jmp end11;"
    		"pg11:"
    		"pop 0x127800c;"
    		"movl $0xb,0x1278010;"
                "mov 0x1278008,%%eax;"
                "mov %%eax,%0;"
    		"end11:"
    		"iret;"
    		"jmp begin11;"
                : "=m" (*d));
  return;
}
void int_handler_12(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
//  kprintf("interrupt handler 12 speaking\n");
    uint32_t *d = &(tss0.eip);
    asm volatile (
    		"begin12:"
    		"mov %%cr0,%%eax;"
    		"and $0x80000000,%%eax;"
    		"cmpl $0x80000000,%%eax;"
    		"je pg12;"
    		"pop 0x27800c;"
    		"movl $0xb,0x278010;"
                "mov 0x278008,%%eax;"
                "mov %%eax,%0;"
    		"jmp end12;"
    		"pg12:"
    		"pop 0x127800c;"
    		"movl $0xb,0x1278010;"
                "mov 0x1278008,%%eax;"
                "mov %%eax,%0;"
    		"end12:"
    		"iret;"
    		"jmp begin12;"
                : "=m" (*d));
  return;
}
void int_handler_13(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
//  kprintf("interrupt handler 13 speaking\n");
    uint32_t *d = &(tss0.eip);
    asm volatile (
    		"begin13:"
    		"mov %%cr0,%%eax;"
    		"and $0x80000000,%%eax;"
    		"cmpl $0x80000000,%%eax;"
    		"je pg13;"
    		"pop 0x27800c;"
    		"movl $0xd,0x278010;"
                "mov 0x278008,%%eax;"
                "mov %%eax,%0;"
    		"jmp end13;"
    		"pg13:"
    		"pop 0x127800c;"
    		"movl $0xd,0x1278010;"
                "mov 0x1278008,%%eax;"
                "mov %%eax,%0;"
    		"end13:"
                "iret;"
    		"jmp begin13;"
                : "=m" (*d));
  return;
}
void int_handler_14(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
//  kprintf("interrupt handler 14 speaking\n");
    uint32_t *d = &(tss0.eip);
    asm volatile (
    		"begin14:"
    		"mov %%cr0,%%eax;"
    		"and $0x80000000,%%eax;"
    		"cmpl $0x80000000,%%eax;"
    		"je pg14;"
    		"pop 0x27800c;"
    		"movl $0xe,0x278010;"
                "mov 0x278008,%%eax;"
                "mov %%eax,%0;"
    		"jmp end14;"
    		"pg14:"
    		"pop 0x127800c;"
    		"movl $0xe,0x1278010;"
                "mov 0x1278008,%%eax;"
                "mov %%eax,%0;"
    		"end14:"
    		"iret;"
    		"jmp begin14;"
                : "=m" (*d));
  return;
}
void int_handler_15(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
//  kprintf("interrupt handler 15 speaking\n");
    uint32_t *d = &(tss0.eip);
    asm volatile (
    		"begin15:"
    		"mov %%cr0,%%eax;"
    		"and $0x80000000,%%eax;"
    		"cmpl $0x80000000,%%eax;"
    		"je pg15;"
    		"movl $0xf,0x278010;"
                "mov 0x278008,%%eax;"
                "mov %%eax,%0;"
    		"jmp end15;"
    		"pg15:"
    		"movl $0xa,0x1278010;"
                "mov 0x1278008,%%eax;"
                "mov %%eax,%0;"
    		"end15:"
    		"iret;"
    		"jmp begin15;"
                : "=m" (*d));
  return;
}
void int_handler_16(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
//  kprintf("interrupt handler 16 speaking\n");
    uint32_t *d = &(tss0.eip);
    asm volatile (
    		"begin16:"
    		"mov %%cr0,%%eax;"
    		"and $0x80000000,%%eax;"
    		"cmpl $0x80000000,%%eax;"
    		"je pg16;"
    		"movl $0x10,0x278010;"
                "mov 0x278008,%%eax;"
                "mov %%eax,%0;"
    		"jmp end16;"
    		"pg16:"
    		"movl $0x10,0x1278010;"
                "mov 0x1278008,%%eax;"
                "mov %%eax,%0;"
    		"end16:"
    		"iret;"
    		"jmp begin16;"
                : "=m" (*d));
  return;
}
void int_handler_17(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
//  kprintf("interrupt handler 17 speaking\n");
    uint32_t *d = &(tss0.eip);
    asm volatile (
    		"begin17:"
    		"mov %%cr0,%%eax;"
    		"and $0x80000000,%%eax;"
    		"cmpl $0x80000000,%%eax;"
    		"je pg17;"
    		"pop 0x27800c;"
    		"movl $0x11,0x278010;"
                "mov 0x278008,%%eax;"
                "mov %%eax,%0;"
    		"jmp end17;"
    		"pg17:"
    		"pop 0x127800c;"
    		"movl $0x11,0x1278010;"
                "mov 0x1278008,%%eax;"
                "mov %%eax,%0;"
    		"end17:"
    		"iret;"
    		"jmp begin17;"
                : "=m" (*d));
  return;
}
void int_handler_18(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
//  kprintf("interrupt handler 18 speaking\n");
    uint32_t *d = &(tss0.eip);
    asm volatile (
    		"begin18:"
    		"mov %%cr0,%%eax;"
    		"and $0x80000000,%%eax;"
    		"cmpl $0x80000000,%%eax;"
    		"je pg18;"
    		"movl $0x12,0x278010;"
                "mov 0x278008,%%eax;"
                "mov %%eax,%0;"
    		"jmp end18;"
    		"pg18:"
    		"movl $0x12,0x1278010;"
                "mov 0x1278008,%%eax;"
                "mov %%eax,%0;"
    		"end18:"
    		"iret;"
    		"jmp begin18;"
                : "=m" (*d));
  return;
}
void int_handler_19(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
//  kprintf("interrupt handler 19 speaking\n");
    uint32_t *d = &(tss0.eip);
    asm volatile (
    		"begin19:"
    		"mov %%cr0,%%eax;"
    		"and $0x80000000,%%eax;"
    		"cmpl $0x80000000,%%eax;"
    		"je pg19;"
    		"movl $0x13,0x278010;"
                "mov 0x278008,%%eax;"
                "mov %%eax,%0;"
    		"jmp end19;"
    		"pg19:"
    		"movl $0x13,0x1278010;"
                "mov 0x1278008,%%eax;"
                "mov %%eax,%0;"
    		"end19:"
    		"iret;"
    		"jmp begin19;"
                : "=m" (*d));
  return;
}

void int_handler_32(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
//  kprintf("interrupt handler 31 speaking\n");
  asm volatile (
                  "begin32:"
                  "add $0,%eax;"
                  "iret;");
  return;
}

void int_handler_20(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
  kprintf("interrupt handler 20 speaking\n");
  return;
}
void int_handler_21(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
  kprintf("interrupt handler 21 speaking\n");
  return;
}
void int_handler_22(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
  kprintf("interrupt handler 22 speaking\n");
  return;
}
void int_handler_23(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
  kprintf("interrupt handler 23 speaking\n");
  return;
}
void int_handler_24(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
  kprintf("interrupt handler 24 speaking\n");
  return;
}
void int_handler_25(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
  kprintf("interrupt handler 25 speaking\n");
  return;
}
void int_handler_26(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
  kprintf("interrupt handler 26 speaking\n");
  return;
}
void int_handler_27(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
  kprintf("interrupt handler 27 speaking\n");
  return;
}
void int_handler_28(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
  kprintf("interrupt handler 28 speaking\n");
  return;
}
void int_handler_29(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
  kprintf("interrupt handler 29 speaking\n");
  return;
}
void int_handler_30(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
  kprintf("interrupt handler 30 speaking\n");
  return;
}
void int_handler_31(uint32_t code, uint32_t eip, uint32_t cs, uint32_t eflags)
{
  kprintf("interrupt handler 31 speaking\n");
  return;
}
