#!/bin/bash

here=$(readlink -f $0)
here=$(dirname "$0")
floppy="$1"
out="$2"
tmp="$3"
dir=$(dirname $2)/time

if [ "$floppy" = "" -o "$out" = "" ]
then
    echo "Invalid argument(s)"
    exit 1
fi

echo "#######################################################################################"
echo ""

md5=$(mtype -i "$floppy" "::kernel.md5")
pre="$tmp/$(basename $out).pre"
post=$(mktemp)

export KEMUFUZZER_KERNEL_VERSION="prot + pag"
export KEMUFUZZER_KERNEL_CHECKSUM="$md5"
export KEMUFUZZER_PRE_STATE="$pre"
export KEMUFUZZER_POST_STATE="$post"
export KEMUFUZZER_TESTCASE_CHECKSUM="no checksum"

#/usr/bin/time -f %e $here/i386-softmmu/qemu -m 4 -fda "$floppy" -nographic $4 > $out.exit
{ TIMEFORMAT='%3R'; time $here/i386-softmmu/qemu -m 4 -fda "$floppy" -nographic $4; } 2>>$dir
ret=$?
if [ $ret -eq 0 ]
then
	mv "$pre" "$out.pre"
	mv "$post" "$out.post"
else
	sed -i '$ d' $dir
fi

rm -f "$bochsrc" "$post"

exit $ret
