################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../cpu/3dnow.o \
../cpu/access.o \
../cpu/access32.o \
../cpu/aes.o \
../cpu/apic.o \
../cpu/arith16.o \
../cpu/arith32.o \
../cpu/arith8.o \
../cpu/bcd.o \
../cpu/bit.o \
../cpu/bit16.o \
../cpu/bit32.o \
../cpu/call_far.o \
../cpu/cpu.o \
../cpu/cpuid.o \
../cpu/crc32.o \
../cpu/crregs.o \
../cpu/ctrl_xfer16.o \
../cpu/ctrl_xfer32.o \
../cpu/ctrl_xfer_pro.o \
../cpu/data_xfer16.o \
../cpu/data_xfer32.o \
../cpu/data_xfer8.o \
../cpu/debugstuff.o \
../cpu/exception.o \
../cpu/fetchdecode.o \
../cpu/flag_ctrl.o \
../cpu/flag_ctrl_pro.o \
../cpu/fpu_emu.o \
../cpu/icache.o \
../cpu/init.o \
../cpu/io.o \
../cpu/iret.o \
../cpu/jmp_far.o \
../cpu/lazy_flags.o \
../cpu/load32.o \
../cpu/logical16.o \
../cpu/logical32.o \
../cpu/logical8.o \
../cpu/mmx.o \
../cpu/msr.o \
../cpu/mult16.o \
../cpu/mult32.o \
../cpu/mult8.o \
../cpu/paging.o \
../cpu/proc_ctrl.o \
../cpu/protect_ctrl.o \
../cpu/resolver.o \
../cpu/ret_far.o \
../cpu/segment_ctrl.o \
../cpu/segment_ctrl_pro.o \
../cpu/shift16.o \
../cpu/shift32.o \
../cpu/shift8.o \
../cpu/smm.o \
../cpu/soft_int.o \
../cpu/sse.o \
../cpu/sse_move.o \
../cpu/sse_pfp.o \
../cpu/sse_rcp.o \
../cpu/sse_string.o \
../cpu/stack16.o \
../cpu/stack32.o \
../cpu/string.o \
../cpu/tasking.o \
../cpu/vm8086.o \
../cpu/vmexit.o \
../cpu/vmx.o \
../cpu/xsave.o 

CC_SRCS += \
../cpu/3dnow.cc \
../cpu/access.cc \
../cpu/access32.cc \
../cpu/access64.cc \
../cpu/aes.cc \
../cpu/apic.cc \
../cpu/arith16.cc \
../cpu/arith32.cc \
../cpu/arith64.cc \
../cpu/arith8.cc \
../cpu/bcd.cc \
../cpu/bit.cc \
../cpu/bit16.cc \
../cpu/bit32.cc \
../cpu/bit64.cc \
../cpu/call_far.cc \
../cpu/cpu.cc \
../cpu/cpuid.cc \
../cpu/crc32.cc \
../cpu/crregs.cc \
../cpu/ctrl_xfer16.cc \
../cpu/ctrl_xfer32.cc \
../cpu/ctrl_xfer64.cc \
../cpu/ctrl_xfer_pro.cc \
../cpu/data_xfer16.cc \
../cpu/data_xfer32.cc \
../cpu/data_xfer64.cc \
../cpu/data_xfer8.cc \
../cpu/debugstuff.cc \
../cpu/exception.cc \
../cpu/fetchdecode.cc \
../cpu/fetchdecode64.cc \
../cpu/flag_ctrl.cc \
../cpu/flag_ctrl_pro.cc \
../cpu/fpu_emu.cc \
../cpu/icache.cc \
../cpu/init.cc \
../cpu/io.cc \
../cpu/iret.cc \
../cpu/jmp_far.cc \
../cpu/lazy_flags.cc \
../cpu/load32.cc \
../cpu/logical16.cc \
../cpu/logical32.cc \
../cpu/logical64.cc \
../cpu/logical8.cc \
../cpu/mmx.cc \
../cpu/msr.cc \
../cpu/mult16.cc \
../cpu/mult32.cc \
../cpu/mult64.cc \
../cpu/mult8.cc \
../cpu/paging.cc \
../cpu/proc_ctrl.cc \
../cpu/protect_ctrl.cc \
../cpu/resolver.cc \
../cpu/ret_far.cc \
../cpu/segment_ctrl.cc \
../cpu/segment_ctrl_pro.cc \
../cpu/shift16.cc \
../cpu/shift32.cc \
../cpu/shift64.cc \
../cpu/shift8.cc \
../cpu/smm.cc \
../cpu/soft_int.cc \
../cpu/sse.cc \
../cpu/sse_move.cc \
../cpu/sse_pfp.cc \
../cpu/sse_rcp.cc \
../cpu/sse_string.cc \
../cpu/stack16.cc \
../cpu/stack32.cc \
../cpu/stack64.cc \
../cpu/string.cc \
../cpu/tasking.cc \
../cpu/vm8086.cc \
../cpu/vmexit.cc \
../cpu/vmx.cc \
../cpu/xsave.cc 

OBJS += \
./cpu/3dnow.o \
./cpu/access.o \
./cpu/access32.o \
./cpu/access64.o \
./cpu/aes.o \
./cpu/apic.o \
./cpu/arith16.o \
./cpu/arith32.o \
./cpu/arith64.o \
./cpu/arith8.o \
./cpu/bcd.o \
./cpu/bit.o \
./cpu/bit16.o \
./cpu/bit32.o \
./cpu/bit64.o \
./cpu/call_far.o \
./cpu/cpu.o \
./cpu/cpuid.o \
./cpu/crc32.o \
./cpu/crregs.o \
./cpu/ctrl_xfer16.o \
./cpu/ctrl_xfer32.o \
./cpu/ctrl_xfer64.o \
./cpu/ctrl_xfer_pro.o \
./cpu/data_xfer16.o \
./cpu/data_xfer32.o \
./cpu/data_xfer64.o \
./cpu/data_xfer8.o \
./cpu/debugstuff.o \
./cpu/exception.o \
./cpu/fetchdecode.o \
./cpu/fetchdecode64.o \
./cpu/flag_ctrl.o \
./cpu/flag_ctrl_pro.o \
./cpu/fpu_emu.o \
./cpu/icache.o \
./cpu/init.o \
./cpu/io.o \
./cpu/iret.o \
./cpu/jmp_far.o \
./cpu/lazy_flags.o \
./cpu/load32.o \
./cpu/logical16.o \
./cpu/logical32.o \
./cpu/logical64.o \
./cpu/logical8.o \
./cpu/mmx.o \
./cpu/msr.o \
./cpu/mult16.o \
./cpu/mult32.o \
./cpu/mult64.o \
./cpu/mult8.o \
./cpu/paging.o \
./cpu/proc_ctrl.o \
./cpu/protect_ctrl.o \
./cpu/resolver.o \
./cpu/ret_far.o \
./cpu/segment_ctrl.o \
./cpu/segment_ctrl_pro.o \
./cpu/shift16.o \
./cpu/shift32.o \
./cpu/shift64.o \
./cpu/shift8.o \
./cpu/smm.o \
./cpu/soft_int.o \
./cpu/sse.o \
./cpu/sse_move.o \
./cpu/sse_pfp.o \
./cpu/sse_rcp.o \
./cpu/sse_string.o \
./cpu/stack16.o \
./cpu/stack32.o \
./cpu/stack64.o \
./cpu/string.o \
./cpu/tasking.o \
./cpu/vm8086.o \
./cpu/vmexit.o \
./cpu/vmx.o \
./cpu/xsave.o 

CC_DEPS += \
./cpu/3dnow.d \
./cpu/access.d \
./cpu/access32.d \
./cpu/access64.d \
./cpu/aes.d \
./cpu/apic.d \
./cpu/arith16.d \
./cpu/arith32.d \
./cpu/arith64.d \
./cpu/arith8.d \
./cpu/bcd.d \
./cpu/bit.d \
./cpu/bit16.d \
./cpu/bit32.d \
./cpu/bit64.d \
./cpu/call_far.d \
./cpu/cpu.d \
./cpu/cpuid.d \
./cpu/crc32.d \
./cpu/crregs.d \
./cpu/ctrl_xfer16.d \
./cpu/ctrl_xfer32.d \
./cpu/ctrl_xfer64.d \
./cpu/ctrl_xfer_pro.d \
./cpu/data_xfer16.d \
./cpu/data_xfer32.d \
./cpu/data_xfer64.d \
./cpu/data_xfer8.d \
./cpu/debugstuff.d \
./cpu/exception.d \
./cpu/fetchdecode.d \
./cpu/fetchdecode64.d \
./cpu/flag_ctrl.d \
./cpu/flag_ctrl_pro.d \
./cpu/fpu_emu.d \
./cpu/icache.d \
./cpu/init.d \
./cpu/io.d \
./cpu/iret.d \
./cpu/jmp_far.d \
./cpu/lazy_flags.d \
./cpu/load32.d \
./cpu/logical16.d \
./cpu/logical32.d \
./cpu/logical64.d \
./cpu/logical8.d \
./cpu/mmx.d \
./cpu/msr.d \
./cpu/mult16.d \
./cpu/mult32.d \
./cpu/mult64.d \
./cpu/mult8.d \
./cpu/paging.d \
./cpu/proc_ctrl.d \
./cpu/protect_ctrl.d \
./cpu/resolver.d \
./cpu/ret_far.d \
./cpu/segment_ctrl.d \
./cpu/segment_ctrl_pro.d \
./cpu/shift16.d \
./cpu/shift32.d \
./cpu/shift64.d \
./cpu/shift8.d \
./cpu/smm.d \
./cpu/soft_int.d \
./cpu/sse.d \
./cpu/sse_move.d \
./cpu/sse_pfp.d \
./cpu/sse_rcp.d \
./cpu/sse_string.d \
./cpu/stack16.d \
./cpu/stack32.d \
./cpu/stack64.d \
./cpu/string.d \
./cpu/tasking.d \
./cpu/vm8086.d \
./cpu/vmexit.d \
./cpu/vmx.d \
./cpu/xsave.d 


# Each subdirectory must supply rules for building sources it contributes
cpu/%.o: ../cpu/%.cc
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


